apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-pv-claim
  namespace: devops-tools
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi